import { ToolHandler } from '../../types/index.js';
import { handleUpdateCapturePolicy } from './handler.js';

export const updateCapturePolicyTool: ToolHandler = {
  definition: {
    name: 'paput_update_capture_policy',
    description:
      'Save the local PaPut capture policy document generated by the client AI from discarded knowledge candidates.',
    inputSchema: {
      type: 'object',
      properties: {
        markdown: {
          type: 'string',
          description: 'Capture policy markdown to save locally.',
        },
      },
      required: ['markdown'],
    },
  },
  handler: handleUpdateCapturePolicy,
};
