import { ToolHandler } from '../../types/index.js';
import { handler } from './handler.js';

export const updateSkillSheetProjectAiSummaryTool: ToolHandler = {
  definition: {
    name: 'paput_update_skill_sheet_project_ai_summary',
    description:
      'Save an AI-generated summary for a PaPut skill sheet project. The summary should be generated by the MCP client AI model.',
    inputSchema: {
      type: 'object',
      properties: {
        project_id: {
          type: 'number',
          description: 'Project ID',
        },
        ai_summary: {
          type: 'string',
          description: 'AI-generated project summary to save',
        },
      },
      required: ['project_id', 'ai_summary'],
    },
  },
  handler,
};
