import { ToolHandler } from '../../types/index.js';
import { handler } from './handler.js';

export const updateSkillSheetPublicProfileTool: ToolHandler = {
  definition: {
    name: 'paput_update_skill_sheet_public_profile',
    description:
      'Save an AI-generated public profile for a PaPut skill sheet. The headline, profile summary, and strength labels should be generated by the MCP client AI model and saved only when the user intends to save them.',
    inputSchema: {
      type: 'object',
      properties: {
        headline: {
          type: 'string',
          description: 'One-line catchphrase summarizing the user',
        },
        profile_summary: {
          type: 'string',
          description: 'Multi-line overall summary of the user',
        },
        strength_labels: {
          type: 'array',
          description: 'Array of strength labels',
          items: {
            type: 'object',
            properties: {
              label: {
                type: 'string',
                description: 'Strength label name',
              },
              description: {
                type: 'string',
                description: 'Strength description',
              },
              category_names: {
                type: 'array',
                items: { type: 'string' },
                description: 'Related category names',
              },
              project_ids: {
                type: 'array',
                items: { type: 'string' },
                description: 'Related project IDs',
              },
            },
            required: ['label'],
          },
        },
      },
    },
  },
  handler,
};
