import { ToolHandler } from '../../types/index.js';
import { handleUpdateDashboardAnalysis } from './handler.js';

export const updateDashboardAnalysisTool: ToolHandler = {
  definition: {
    name: 'paput_update_dashboard_analysis',
    description:
      'Save a dashboard analysis result generated by the MCP client AI model.',
    inputSchema: {
      type: 'object',
      properties: {},
    },
  },
  handler: handleUpdateDashboardAnalysis,
};
